### ISSUE TITLE
failure on clone

### ISSUE THREAD

**Issue by netskink** [ZOSOpenTools/gpgport#15]
Failure when doing git clone 

> $ git clone https://github.com/ZOSOpenTools/gpgport
> Cloning into 'gpgport'...
> fatal: unable to access 'https://github.com/ZOSOpenTools/gpgport/': error setting certificate file: > /z/jd895801/zopen/usr/local/zopen/git/git-2.41.0.20230906_213139.zos/cacert.pem

**Comment by IgorTodorovskiIBM** [comment]
Is this still an issue with the latest git?

**Comment by netskink** [comment]
It was at the time. I'm at airport now but I'll revisit upon my return.

**Comment by netskink** [comment]
It works fine now.
